name: Beta
on:
  push:
    branches:
      - beta
jobs:
  deploy:
    name: Beta Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install PHP and dependencies
      run: sudo apt-get update && sudo apt-get install php php-mbstring php-xml

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Install NPM Dependencies
      run: npm install
    - name: Build Scripts
      run: npm run release
    - name: Release Trunk
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: beta-trunk
        FOLDER: deploy
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: ZIP
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: beta-release
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
