name: Crowdin Translation Upload

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger this action

jobs:
  upload-pot-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload translations to Crowdin
      uses: crowdin/github-action@v2
      with:
        upload_sources: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
